server:
  port: 9002

spring:
  datasource:

    url: jdbc:mysql://localhost:3306/ceo?serverTimezone=Asia/Seoul
    username: root
    password: "[dhqclwoa12]"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true